### ISSUE TITLE
FFI?

### ISSUE THREAD

**Issue by ghost** [ion-lang/ion#2]
This looks like a promising language! Is it possible to use existing JS libraries from within Ion?

**Comment by joaomilho** [comment]
Yes. ion's philosophy is not to be a completely different lang that require some boilerplate to interact with vanilla JS. In this sense, ion is the "functional" coffeescript.

Try this:
```js
// test.ion
fs = require('fs')
put(fs.readFileSync('test.ion', 'utf8'))
```

```bash
$ ion test.ion
fs = require('fs')
put(fs.readFileSync('test.ion', 'utf8'))
```

The same is true for web builds, using ion along with webpack.

**Comment by joaomilho** [comment]
Important to say that the opposite is also true. If you have an ion module exporting something (like https://github.com/ion-lang/ion/blob/master/test/fixtures/samples/export.ion) and you do a require in a JS file (`require('someModule.ion')`) – using webpack – it will work fine.
